Add support for RT patches
Frogging-Family/linux-tkg pull request #380
Opened 2021-12-06 13:15 UTC by X9VoiD

## Changes

 - Added `_preempt_rt` option.
 - Added `_preempt_rt_force` option.
 - Changed some `typeset` variables into globals.

This PR pulls the patches from [upstream RT](https://cdn.kernel.org/pub/linux/kernel/projects/rt/) and then applies them as early as possible. There are checks to see if upstream supports the kernel version being compiled and the check for kernel subversion can be bypassed with `_preempt_rt_force=1`.

To maintain the new feature, updating the entries in `_rt_subver_map` and `_rt_rev_map` will be enough for most cases.

2021-12-06 13:35 UTC, ptr1337 commented
Did you checked if its is applying correctly with the other patches which are used?

Since RT wont be supported by most scheduler, at CFS and Cacule got a RT patch

2021-12-06 14:00 UTC, X9VoiD commented
I just added a warning in the config that it might not support other schedulers. Skip non-cfs cpu sched patches when PREEMPT_RT is enabled?

2021-12-06 16:33 UTC, gghhkm requested changes
It should specify that CFS is the fully supported scheduler. Saying "Other CPU schedulers might not be compatible.." leaves room for confusion on what is supported.

2021-12-06 21:11 UTC, X9VoiD commented
The PREEMPT_RT code in 5.15 has no tunable config yet to enable it afaik. Please do tell if I'm wrong about it.

And as to about why the PR is submitted to this repo, it's because this pulls the patches from upstream. I am not against submitting it as a community patch tho. Will gladly comply with what people think is for the better.

2021-12-06 23:16 UTC, ptr1337 commented
> The PREEMPT_RT code in 5.15 has no tunable config yet to enable it afaik. Please do tell if I'm wrong about it.
> 
> And as to about why the PR is submitted to this repo, it's because this pulls the patches from upstream. I am not against submitting it as a community patch tho. Will gladly comply with what people think is for the better.

Why it should it not able to enable the RT preempt ? 
Just run makenconfig, select under general settings config expert and go to preempt and enable preempt rt. there is the magic.

2021-12-07 00:19 UTC, ptr1337 commented
Here you will find for cacule 5.15 and also 5.16 RT patches

https://github.com/CachyOS/cacule-cpu-scheduler/tree/master/patches/CacULE

2021-12-07 03:30 UTC, X9VoiD commented
> Why it should it not able to enable the RT preempt ? Just run makenconfig, select under general settings config expert and go to preempt and enable preempt rt. there is the magic.

I'm not sure what magic you're talking about, but it doesn't work.

![image](https://user-images.githubusercontent.com/10338031/144956871-f1ee5cd9-583d-49e1-a84d-8860c847e693.png)
![image](https://user-images.githubusercontent.com/10338031/144957104-ce347fe4-36b6-44de-9826-42599362249d.png)
![image](https://user-images.githubusercontent.com/10338031/144957128-76996763-b925-4d81-a800-394f1e2c1678.png)
![image](https://user-images.githubusercontent.com/10338031/144957146-6438b3d2-75d0-4990-9212-781f302577f2.png)

Same results on `nconfig`.

![image](https://user-images.githubusercontent.com/10338031/144957708-2f91e9bd-1382-4db7-baf0-a3e9165a9302.png)

The reason being...
![image](https://user-images.githubusercontent.com/10338031/144957745-1135daab-2c4b-4156-9521-67fad6851d7d.png)
`ARCH_SUPPORTS_RT` is intentionally not defined anywhere and I don't think it would be a good idea to jump the gun when the creators of the patch itself gated the feature, and merged to the kernel like that. `ARCH_SUPPORTS_RT` only gets enabled by applying the full `PREEMPT_RT` patchset. You may see it for yourself [here](https://cdn.kernel.org/pub/linux/kernel/projects/rt/5.15/).

So anyway, I still tried `_enable "EXPERT" "ARCH_SUPPORTS_RT" "PREEMPT_RT"` to see if we can force it. It did not work and made a fallback to `PREEMPT_NONE`.

2021-12-07 07:34 UTC, ptr1337 commented
There was never a config with from the RT-devel branch. 

I will show you when I’m home from work.

2021-12-07 08:46 UTC, X9VoiD commented
You're contradicting yourself.

> Why it should it not able to enable the RT preempt ?
Just run makenconfig, select under general settings config expert and go to preempt and enable preempt rt. there is the magic.

At first you said that the `PREEMPT_RT` config is tunable on vanilla 5.15. I showed you that it isn't.

> There was never a config with from the RT-devel branch.
> 
> I will show you when I’m home from work.

Now you're telling me there never was a config to begin with.
Which one of your statements should I believe now?

Also, after patching the kernel with the full `PREEMPT_RT` patchset, the option becomes available as expected.
![image](https://user-images.githubusercontent.com/10338031/144993583-4d90ce6d-78ae-4444-a82f-4530315b49b3.png)
![image](https://user-images.githubusercontent.com/10338031/144994583-cf8a3c18-b158-44bf-bc7c-a1b20b592619.png)

If you want sources then [help yourself](https://cdn.kernel.org/pub/linux/kernel/projects/rt/5.15/patch-5.15.5-rt22.patch.gz).
> patch-5.15.5-rt22.patch
![image](https://user-images.githubusercontent.com/10338031/144994905-0a9a29f9-d538-44d0-9e10-2f0341c1a1ee.png)
https://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-rt-devel.git/tree/patches/x86__Allow_to_enable_RT.patch?h=linux-5.16.y-rt-patches

2021-12-07 10:07 UTC, ptr1337 commented
https://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-rt-devel.git/tree/kernel/Kconfig.preempt?h=linux-5.15.y-rt

Its already in the 5.15 kernel as option in.

2021-12-07 10:25 UTC, ptr1337 commented
https://ibb.co/3dSgkyn

Just tested on my server. worked directly with my kernel which you found. Also it was directly enabled without any changes in makenconfig ;)

https://github.com/CachyOS/linux-cachyos/tree/master/linux-cachyos-rt

2021-12-07 13:00 UTC, X9VoiD commented
> https://git.kernel.org/pub/scm/linux/kernel/git/rt/linux-rt-devel.git/tree/kernel/Kconfig.preempt?h=linux-5.15.y-rt
> 
> Its already in the 5.15 kernel as option in.

This is part of the patchset, of course it will be there.

> Just tested on my server. worked directly with my kernel which you found. Also it was directly enabled without any changes in makenconfig ;)

Of course it will be, you're using the [full `PREEMPT_RT` patchset](https://github.com/CachyOS/linux-cachyos/blob/6bd633610b19ae22535eaa4c96286aba1ed17cae/linux-cachyos-rt/PKGBUILD#L131). It still contradicts your original statement that "`PREEMPT_RT` is already a feature that can be enabled on vanilla 5.15.x kernel.", which is *clearly not*. I am not sure if this is just a language barrier, but you don't have to prove yourself anymore. The sources are already out there.

Just to clarify, I am not saying that `PREEMPT_RT` doesn't exist in 5.15. What I am saying is it's not configurable without the full patchset, and is intended to be this way by the authors themselves.

Anyway, you trying to prove "vanilla 5.15 don't need the patchset to enable `PREEMPT_RT`" is completely out of topic as this concerns enabling the full version of it. Will be glad if it ends here, thank you. On that note, I'm willing to migrate this PR to community-patches if it's more desirable to do so.

2021-12-07 14:08 UTC, ptr1337 commented
I dont know where is your problem ?
ill just use that patch:
https://mirrors.edge.kernel.org/pub/linux/kernel/projects/rt/5.15/
which are the correct patches to use on the vanilla kernel. you just need to modify maybe your config to get it instantly shown. 

Try this config on the vanilla kernel + the 5.15-rt patch and you will see the magic. 

https://raw.githubusercontent.com/CachyOS/linux-cachyos/master/linux-cachyos-rt/config

2021-12-07 14:23 UTC, X9VoiD commented
Definitely language barrier, I'm literally using upstream patches, the original patch made directly by the authors of `PREEMPT_RT`. And it immediately works. I wouldn't be submitting a PR if it wasn't working.

What I have problems with is your false argument about 5.15 having configurable `PREEMPT_RT` by default when it's literally gated. I already showed all the sources. Just stop. You're just digging yourself a deeper grave. And stop shoving your patches on other people's faces, please, it's so unprofessional and impolite.

2021-12-07 15:14 UTC, ptr1337 commented
I talked about your PR and not about a vanilla non-patched 5.15. I just said that MOST RT stuff already implemented into the 5.15 and will be also more into 5.16 and 5.17. 

And at your PR you are using the the RT patches which i referred to.

2021-12-07 15:46 UTC, gghhkm approved these changes

2021-12-12 14:18 UTC, Tk-Glitch commented
Okay, let's go. Thanks @X9VoiD and @gghhkm :frog: :heart:

2021-12-12 14:18 UTC, merged